Merge branch 'dev' into master
Galish/loyalty-system pull request #9
Opened 2023-12-20 18:41 UTC by Galish

2023-12-23 16:43 UTC, capsulated requested changes
Всё круто: хорошо читаемый код, пакеты структурированы, определены error'ы, сервисы, хендлеры 👍

Есть замечания по организации моделей (entity). Комментарии добавил и так как тема абстрактная, если с чем-то не согласен - ответ на комментарий приветствуется! )

2023-12-23 16:43 UTC, capsulated commented on internal/accrual/service.go
> +	limiterInterval time.Duration = 1 * time.Second
Это в конфиг перенести

2023-12-23 16:43 UTC, capsulated commented on internal/model/accrual.go
> +package model
Один пакет для всех моделей плохо тем, что пакет в итоге "разбухнет" (если бы это был реальный проект). Лучше модели на уровне одного пакета определять, в случае, если они только в этом одном пакете используются, по примеру `accrualResponse`. А если модели используются во многих пакетах, то как-то их можно по категориям разбить, по разным пакетам, или подпакетам.

В рамках данной работы, это не критично, но всегда над планированием пакетов нужно задумываться, так как папка в go - это что-то типа namespace, а при импорте пакет импортируется целиком

2023-12-23 16:43 UTC, capsulated commented on internal/model/order.go
> +type Order struct {
К одной модели Order можно "прилепить" поведение (useCase), скажем преобразование  json или в  response

2023-12-23 16:43 UTC, capsulated commented on internal/order/orders.go
> +package order
Вот в пакете Order лучше определить модели order'а. Можно отделить модель (entity) от поведения (usecase) в разных пакетах или в подпакете

2023-12-23 16:43 UTC, capsulated commented on internal/repository/psql/bootstrap.go
> +			CREATE TABLE IF NOT EXISTS users (
Обычно в init.sql такое и он в контейнере запускается при старте базы. Но в нашем случае можно прочитать из файла init.sql (в случае, если база пустая)

2023-12-25 14:04 UTC, Galish commented on internal/accrual/service.go
> +	limiterInterval time.Duration = 1 * time.Second
✅ Готово

2023-12-25 14:04 UTC, Galish commented on internal/repository/psql/bootstrap.go
> +			CREATE TABLE IF NOT EXISTS users (
✅ Готово

2023-12-25 14:31 UTC, Galish commented on internal/model/accrual.go
> +package model
❓ т.е. как вариант создать отдельную поддиректорию для каждой сущности?
```
model
  |- accrual
  |- balance
  |- order
  |- user
```

2023-12-25 14:36 UTC, Galish commented on internal/order/orders.go
> +package order
❓ если модели разместить в пакете `/order`, то возникнет проблема циклического импорта, т.к. модели используются и в репозитории, а сервис вызывает методы репозитория.

2023-12-25 14:39 UTC, Galish commented on internal/model/order.go
> +type Order struct {
❓ под `useCase` подразумевается отдельная структура/пакет? Или же доп. методы существующей структуры? Где можно почитать об этом подробнее?

2023-12-26 17:55 UTC, capsulated commented on internal/model/accrual.go
> +package model
По моему мнению, да, лучше так, что бы несколько пакетов было. В принципе это резонирует с Entity из DDD. И импортировать можно их глобально, на любом уровне

2023-12-26 18:25 UTC, capsulated commented on internal/model/order.go
> +type Order struct {
Да, всё верно - это поведение объекта. Паттернов реализации много, [тут](https://habr.com/ru/articles/718916/) можно глянуть про разные подходы. Плюс сами реализации подходов могут отличаться, так как это всё же абстракция, и как наложить подход на программный код - творческая задача.

Изначально, можно просто назначить методы типу (указав в функции экземпляр или указатель на тип) - это самый простой способ и базовый подход. Далее, можно разделять поведение на пакеты UseCase, в принципе в статье выше есть примеры. Но какого-то эталонного кода реализации подходов нет, так как каждый реализует с какими-то отличиями

2023-12-26 18:42 UTC, capsulated commented on internal/order/orders.go
> +package order
Как только появляется объект, зависимость на который больше одного - то это признак для создания пакета. Выше уже скинул статью, где описаны подходы с глобальным уровнем Entity/Model

2023-12-26 18:42 UTC, capsulated commented on internal/repository/psql/bootstrap.go
> +			CREATE TABLE IF NOT EXISTS users (
Это не критично, но пригодится)

2023-12-26 18:46 UTC, capsulated requested changes
Всё супер.

По моделям написал коммент. Если не согласен - то можно созвонится, обсудить, мне бы тоже было интересно выслушать твоё мнение. В принципе, и в текущей реализации работу можно уже принять, так как в текущем проекте можно и оставить один пакет для моделей, но это уменьшает возможности масштабирования кодовой базы

2024-01-06 11:24 UTC, Galish commented
Внес правки в структуру проекта согласно рекомендациям по организации системной архитектуры **Clean Architecture** (точнее то, как я ее понял).

2024-01-09 19:53 UTC, capsulated approved these changes
Всё отлично

Апрув, но оставил один коммент

2024-01-09 19:53 UTC, capsulated commented on internal/http/middleware/auth.go
> +	return func(h http.Handler) http.Handler {
Двойная обёртка для middleware точно нужна?
```go
...
func WithAuthChecker(secretKey string) func(http.Handler) http.Handler {
   return func(h http.Handler) http.Handler {
      return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { ... })
   }
}        
```
🥴

2024-01-09 19:53 UTC, capsulated commented on internal/http/middleware/logger.go
> +func WithRequestLogger(h http.Handler) http.Handler {
А тут ок

2024-01-10 16:38 UTC, Galish commented on internal/http/middleware/auth.go
> +	return func(h http.Handler) http.Handler {
Разница в том, что при инициализации `WithAuthChecker` я передаю ключ из конфига:
```
r.Use(middleware.WithAuthChecker(cfg.SecretKey))
r.Use(middleware.WithRequestLogger)
```

2024-01-12 06:14 UTC, merged